### ISSUE TITLE
Error setting the covariance.

### ISSUE THREAD

**Issue by shivaway** [r-quantities/errors#33]
I'm working through some of the examples found in this [blog](https://www.statforbiology.com/2019/stat_general_thedeltamethod/).  The package was working as expected up until the third example.

`library(errors)`

`x<- 3.1`
`w<-3.4`
`errors(x) <- 0.8`
`errors(w) <- 0.31`

That part is good.  Where it all falls apart is where I try to assign the covariance:

`covar(x,w) <- 0.55`

I get the following error:

Error in `covar<-.errors`(`*tmp*`, w, value = 0.55) : 
  value/errors(x)/errors(y) <= 1 is not TRUE

I'm not sure why this should be tested if it being assigned.

**Comment by Enchufa2** [comment]
The correlation is defined as

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/ba0fe9f572cc2a4fd3c11922a7aa3eac69f192d5)

In this case, `covar(x, w) / (errors(x) * errors(w)) = 0.55 / (0.8 * 0.31) = 2.22`, but the correlation is bounded between -1 and 1. That's why this check is in place. And this means that this correlation value must be wrong.

**Comment by shivaway** [comment]
Thanks for point out the obvious to the dummy (me)!  That'll teach me to blindly follow examples....
Thanks again,
Shawn Way
    On Tuesday, May 28, 2019, 3:34:23 PM CDT, Iñaki Ucar <notifications@github.com> wrote:  
 
 
The correlation is defined as



In this case, covar(x, w) / (errors(x) * errors(w)) = 0.55 / (0.8 * 0.31) = 2.22, but the correlation is bounded between -1 and 1. That's why this check is in place. And this means that this correlation value must be wrong.

**Comment by Enchufa2** [comment]
No problem!
